chatGPTAccountPool:
    email: 2648142550@qq.com
    password: Dou88*OpenAi
    session_token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9
chatPrivateTiggerKeyword: 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
openAIProxy: ""